language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: nightly
  - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpunit --testsuite=sniff_tests

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 7.1"

cache:
  directories:
    - $HOME/.composer/cache
