language: php

matrix:
  include:
  - php: 5.3
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

script:
  - echo "No tests implemented"

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 5.3"

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb