language: php

matrix:
  include:
    - dist: focal
      php: 8.2
      env: LIBONIG_INSTALL=1

  fast_finish: true

before_install:
  - if [ -n "$LIBONIG_INSTALL" ]; then sudo apt-get install libonig5; fi
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 8.2"

cache:
  directories:
    - $HOME/.composer/cache
